# Generated by Django 4.1 on 2022-08-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mp", "0010_alter_apikey_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Daily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("sku", models.IntegerField(null=True)),
                ("product_id", models.IntegerField(null=True)),
                ("stocks", models.IntegerField(default=0)),
                ("selfbuy_cnt", models.IntegerField(default=0)),
                (
                    "selfbuy_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "premium",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "rassrochka",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "adv_promo_bid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("adv_promo_visibility", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mp.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "sku"],
                "unique_together": {("shop", "date", "sku")},
            },
        ),
    ]
