# Generated by Django 4.1 on 2022-08-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daily",
            name="product_id",
        ),
        migrations.AlterField(
            model_name="daily",
            name="adv_promo_bid",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="daily",
            name="adv_promo_visibility",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="daily",
            name="premium",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="daily",
            name="rassrochka",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="daily",
            name="selfbuy_amount",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="daily",
            name="selfbuy_cnt",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="daily",
            name="stocks",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
