# Generated by Django 4.1 on 2022-08-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_daily_product_id_alter_daily_adv_promo_bid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daily",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="daily",
            name="updated_at",
        ),
    ]
