# Generated by Django 4.0.3 on 2022-03-26 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_token",
                    models.CharField(
                        choices=[("ozon", "Ozon"), ("wb", "Wildberries")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("api_client_id", models.CharField(db_index=True, max_length=64)),
                ("api_key", models.CharField(db_index=True, max_length=256)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "shop_token", "name"],
                "unique_together": {("user", "shop_token", "api_client_id")},
            },
        ),
    ]
