# Generated by Django 4.0.3 on 2022-04-07 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ozon", "Ozon API"),
                            ("performance", "Ozon Performance API"),
                            ("wb_x32", "WB x32 API"),
                            ("wb_x64", "WB x64 API"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("client_id", models.CharField(db_index=True, max_length=128)),
                ("client_secret", models.CharField(db_index=True, max_length=256)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mp.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "type", "name"],
                "unique_together": {("shop", "client_id")},
            },
        ),
    ]
