# Generated by Django 4.0.3 on 2022-04-07 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mp", "0002_apikey"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shop",
            unique_together={("user", "shop_token")},
        ),
        migrations.RemoveField(
            model_name="shop",
            name="api_client_id",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="api_key",
        ),
    ]
