# Generated by Django 4.0.3 on 2022-04-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mp", "0003_alter_shop_unique_together_remove_shop_api_client_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Selfbuy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.CharField(max_length=128)),
                ("dt_buy", models.DateField(null=True)),
                ("dt_take", models.DateField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mp.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["dt_buy", "order"],
                "unique_together": {("shop", "order")},
            },
        ),
    ]
