# Generated by Django 4.0.3 on 2022-04-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mp", "0004_selfbuy"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shop",
            unique_together=set(),
        ),
    ]
