# Generated by Django 4.0.4 on 2022-05-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mp", "0005_alter_shop_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfbuy",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="selfbuy",
            name="offer_id",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
