# Generated by Django 4.0.3 on 2022-05-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mp", "0006_selfbuy_name_selfbuy_offer_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={"ordering": ["-is_active", "id"]},
        ),
    ]
