# Generated by Django 4.0.4 on 2022-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mp", "0007_alter_shop_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfbuy",
            name="offer_id",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
