# Generated by Django 4.0.5 on 2022-06-11 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mp", "0008_alter_selfbuy_offer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="disabled_till",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
