# Generated by Django 4.0.5 on 2022-06-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mp", "0009_apikey_disabled_till"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={"ordering": ["-is_active", "shop", "type", "name"]},
        ),
    ]
