# Generated by Django 4.1 on 2022-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mp", "0010_alter_apikey_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfbuy",
            name="status",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
